development:
  secret_key_base: 5b661a15007e96ecb56afd515eb49be7ca8126807d25fcc0be6343c304232a669b39d09ac94b545dda8f37a06f1fc2d4976b2fd8fc3538f01f13a57c68cc66c2
  access_key_id: AKIAJT7QYGBOAX2AFJBA
  secret_access_key: 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
  bucket_name: jatin-infotech
test:
  secret_key_base: 38f1903e62621ce854fe767a2a49bc34524ba4c9b99b3595ca0ad578b3c50b2597a61c95507c43da42a7f4c299d011294b8ed4bf00d08a997a410bb6857db21a
  access_key_id: AKIAJT7QYGBOAX2AFJBA
  secret_access_key: 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
  bucket_name: jatin-infotech

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  bucket_name: <%= ENV["BUCKET_NAME"] %>
