development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  bucket_name: <%= ENV["BUCKET_NAME"] %>
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  bucket_name: <%= ENV["BUCKET_NAME"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  bucket_name: <%= ENV["BUCKET_NAME"] %>
