# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b661a15007e96ecb56afd515eb49be7ca8126807d25fcc0be6343c304232a669b39d09ac94b545dda8f37a06f1fc2d4976b2fd8fc3538f01f13a57c68cc66c2

test:
  secret_key_base: 38f1903e62621ce854fe767a2a49bc34524ba4c9b99b3595ca0ad578b3c50b2597a61c95507c43da42a7f4c299d011294b8ed4bf00d08a997a410bb6857db21a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
